### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by jakesjews** [brunch/coffee-script-brunch#20]
Could we get a new release with the update to coffee-script 1.9?

**Comment by paulmillr** [comment]
Yes. Would you submit a PR?

**Comment by jakesjews** [comment]
I had a PR that was merged on January 29th that updated to Coffeescript 1.9 it just hasn't been published to NPM

**Comment by es128** [comment]
oops... sorry :blush:

**Comment by jakesjews** [comment]
No problem its easy to forget. I just wanted to leave a reminder.
