### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by connorblack** [brunch/coffee-script-brunch#24]
I run into this issue when building brunch:

```
rejecting for TypeError: Cannot read property 'charCodeAt' of undefined
```

I'm running Mac OSX 10.11.3 (15D21), node 5.0.0 and coffee-script-brunch 2.0.0.

If I downgrade to coffee-script-brunch 1.8.3 and run with `--debug` I can see the build process randomly hanging on a different `.coffee` file every time.

**Comment by connorblack** [comment]
```
  brunch:pipeline Compiling 'app/views/base/CollectionView.coffee' with 'CoffeeScriptCompiler' +0ms
rejecting for TypeError: Cannot read property 'charCodeAt' of undefined
  brunch:pipeline Compiling 'app/views/base/ItemView.coffee' with 'CoffeeScriptCompiler' +0ms
rejecting for TypeError: Cannot read property 'charCodeAt' of undefined
  brunch:pipeline Compiling 'app/views/base/CompositeView.coffee' with 'CoffeeScriptCompiler' +0ms
rejecting for TypeError: Cannot read property 'charCodeAt' of undefined
```

**Comment by connorblack** [comment]
Running `coffee app/*` yields no errors.

**Comment by paulmillr** [comment]
@goshakkk

**Comment by goshakkk** [comment]
@connorblack may I ask you to share a minimal subset of your app that reproduces the issue? The chaplin client for Ostio (https://github.com/paulmillr/ostio-chaplin) is written in CoffeeScript and uses the latest brunch and coffee-script-brunch `^2.0.0`, and builds/works without a problem

**Comment by goshakkk** [comment]
Actually, I was able to get that error by running brunch 1.8.2 with coffee-script-brunch 2.0.0. 

Plugins versioned 2.x.x are meant to be run with brunch 2 only.
